# Spring Boot configuration
spring:
  application:
    name: Backend Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: eurhainez@gmail.com
    password: tklcyemmihwvhslh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backend_service
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port
  error:
    include-binding-errors: always
    include-message: always
